set deviceconfig system hostname PA-DATACENTER-03
set deviceconfig system ip-address 203.0.113.10
set deviceconfig system netmask 255.255.255.0
set deviceconfig system default-gateway 203.0.113.1
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 203.0.113.123
set deviceconfig system login-banner "Authorized personnel only."
set deviceconfig system service disable-telnet yes
set deviceconfig system service disable-http yes
set deviceconfig system ssh service enable yes
set deviceconfig system ssh service protocol-version v2
set deviceconfig system session-timeout 20
set deviceconfig system snmp-setting access-setting version v3
set deviceconfig system syslog-service server 203.0.113.60
set network interface ethernet ethernet1/1 layer3 ip 203.0.113.10/24
set network interface ethernet ethernet1/1 layer3 interface-management-profile OUTSIDE-MGMT
set network profiles interface-management-profile OUTSIDE-MGMT https yes
set network profiles interface-management-profile OUTSIDE-MGMT ssh yes
set network profiles interface-management-profile OUTSIDE-MGMT permitted-ip 203.0.113.0/24
set network profiles interface-management-profile OUTSIDE-MGMT ping no
set network profiles interface-management-profile OUTSIDE-MGMT http no
set network profiles interface-management-profile OUTSIDE-MGMT telnet no
set mgt-config password-complexity enabled yes
set mgt-config password-complexity minimum-length 10
