set deviceconfig system hostname PA-BRANCH-02
set deviceconfig system ip-address 198.51.100.10
set deviceconfig system netmask 255.255.255.0
set deviceconfig system default-gateway 198.51.100.1
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address pool.ntp.org
set deviceconfig system service disable-telnet no
set deviceconfig system service disable-http no
set deviceconfig system ssh service enable yes
set deviceconfig system ssh service protocol-version v1
set deviceconfig system session-timeout 60
set deviceconfig system snmp-setting access-setting version v2c
set deviceconfig system syslog-service server 198.51.100.60
set deviceconfig system login-banner "Welcome"
set network interface ethernet ethernet1/1 layer3 ip 198.51.100.10/24
set network interface ethernet ethernet1/1 layer3 interface-management-profile WAN-MGMT
set network profiles interface-management-profile WAN-MGMT http yes
set network profiles interface-management-profile WAN-MGMT https yes
set network profiles interface-management-profile WAN-MGMT ssh yes
set network profiles interface-management-profile WAN-MGMT ping yes
