set deviceconfig system hostname PA-HQ-FW-04
set deviceconfig system ip-address 10.10.10.10
set deviceconfig system netmask 255.255.255.0
set deviceconfig system default-gateway 10.10.10.1
set deviceconfig system dns-setting servers primary 10.10.10.53
set deviceconfig system dns-setting servers secondary 10.10.10.54
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 10.10.20.20
set deviceconfig system ntp-servers secondary-ntp-server ntp-server-address 10.10.20.21
set deviceconfig system login-banner "This system is restricted to authorized users."
set deviceconfig system permitted-ip 10.10.0.0/16
set deviceconfig system service disable-telnet yes
set deviceconfig system service disable-http yes
set deviceconfig system ssh service enable yes
set deviceconfig system ssh service protocol-version v2
set deviceconfig system session-timeout 15
set deviceconfig system snmp-setting access-setting version v3
set deviceconfig system syslog-service server 10.10.30.10
set deviceconfig system syslog-service server 10.10.30.11
set mgt-config password-complexity enabled yes
set mgt-config password-complexity minimum-length 12
set mgt-config password-complexity minimum-uppercase-letters 1
set mgt-config password-complexity minimum-lowercase-letters 1
set mgt-config password-complexity minimum-numeric-letters 1
set mgt-config password-complexity minimum-special-characters 1
set network interface ethernet ethernet1/1 layer3 ip 10.10.10.10/24
set network interface ethernet ethernet1/1 layer3 interface-management-profile HQ-MGMT
set network profiles interface-management-profile HQ-MGMT https yes
set network profiles interface-management-profile HQ-MGMT ssh yes
set network profiles interface-management-profile HQ-MGMT ping no
set network profiles interface-management-profile HQ-MGMT permitted-ip 10.10.0.0/16
