set deviceconfig system hostname PA-SECURITY-05
set deviceconfig system ip-address 172.16.50.10
set deviceconfig system netmask 255.255.255.0
set deviceconfig system default-gateway 172.16.50.1
set deviceconfig system ntp-servers primary-ntp-server ntp-server-address 172.16.60.10
set deviceconfig system ntp-servers secondary-ntp-server ntp-server-address 172.16.60.11
set deviceconfig system login-banner "WARNING: Authorized access only. Disconnect immediately if unauthorized."
set deviceconfig system permitted-ip 172.16.0.0/16
set deviceconfig system permitted-ip 10.50.0.0/16
set deviceconfig system service disable-telnet yes
set deviceconfig system service disable-http yes
set deviceconfig system ssh service enable yes
set deviceconfig system ssh service protocol-version v2
set deviceconfig system session-timeout 12
set deviceconfig system snmp-setting access-setting version v3
set deviceconfig system syslog-service server 172.16.70.10
set deviceconfig system syslog-service server 172.16.70.11
set mgt-config password-complexity enabled yes
set mgt-config password-complexity minimum-length 16
set mgt-config password-complexity minimum-uppercase-letters 2
set mgt-config password-complexity minimum-lowercase-letters 2
set mgt-config password-complexity minimum-numeric-letters 2
set mgt-config password-complexity minimum-special-characters 2
set network interface ethernet ethernet1/1 layer3 ip 172.16.50.10/24
set network interface ethernet ethernet1/1 layer3 interface-management-profile TRUSTED-MGMT
set network profiles interface-management-profile TRUSTED-MGMT https yes
set network profiles interface-management-profile TRUSTED-MGMT ssh yes
set network profiles interface-management-profile TRUSTED-MGMT ping no
set network profiles interface-management-profile TRUSTED-MGMT permitted-ip 172.16.0.0/16
set network interface ethernet ethernet1/2 layer3 ip 172.16.80.10/24
set network interface ethernet ethernet1/2 layer3 interface-management-profile DMZ-MGMT
set network profiles interface-management-profile DMZ-MGMT https no
set network profiles interface-management-profile DMZ-MGMT ssh no
set network profiles interface-management-profile DMZ-MGMT ping no
set network profiles interface-management-profile DMZ-MGMT permitted-ip 172.16.80.0/24
