system {
    host-name SRX-HQ-FW-04;
    domain-name hq.example;
    services {
        ssh {
            protocol-version v2;
            root-login deny;
            connection-limit 20;
        }
        web-management {
            https {
                interface fxp0.0;
            }
        }
    }
    login {
        message "This system is restricted to authorized users.";
    }
    ntp {
        server 10.10.20.20;
        server 10.10.20.21;
    }
    syslog {
        host 10.10.30.10 {
            any info;
            authorization info;
        }
        host 10.10.30.11 {
            any info;
            authorization info;
        }
    }
    authentication-order [ radius password ];
}
access {
    profile MGMT-ADMIN {
        allow-address 10.10.0.0/16;
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 10.10.10.10/24;
            }
        }
    }
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 10.10.11.10/24;
            }
        }
    }
}
protocols {
    lldp {
        interface ge-0/0/0;
    }
}
