system {
    host-name SRX-SECURITY-05;
    services {
        ssh {
            protocol-version v2;
            root-login deny;
            connection-limit 15;
        }
        web-management {
            https {
                interface fxp0.0;
            }
        }
    }
    login {
        message "WARNING: Authorized access only. Disconnect immediately if unauthorized.";
    }
    ntp {
        server 172.16.60.10;
        server 172.16.60.11;
    }
    syslog {
        host 172.16.70.10 {
            any info;
            interactive-commands info;
        }
        host 172.16.70.11 {
            any info;
            interactive-commands info;
        }
    }
    authentication-order [ tacplus password ];
}
access {
    profile TRUSTED-MGMT {
        allow-address 172.16.0.0/16;
        allow-address 10.50.0.0/16;
    }
}
interfaces {
    fxp0 {
        unit 0 {
            family inet {
                address 172.16.50.10/24;
            }
        }
    }
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 172.16.80.10/24;
            }
        }
    }
}
protocols {
    lldp {
        interface ge-0/0/0;
    }
    rstp {
        interface all;
    }
}
routing-options {
    static {
        route 0.0.0.0/0 next-hop 172.16.50.1;
    }
}
