system {
    host-name SRX-BRANCH-02;
    services {
        telnet;
        web-management {
            http;
        }
        ssh {
            protocol-version v1;
            root-login allow;
        }
    }
    login {
        message "Welcome";
    }
    ntp {
        server pool.ntp.org;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 198.51.100.10/24;
            }
        }
    }
}
protocols {
    lldp {
        interface all;
    }
}
