system {
    host-name SRX-EDGE-01;
    domain-name corp.example;
    services {
        ssh {
            protocol-version v2;
            root-login deny;
            connection-limit 10;
        }
        web-management {
            http {
                interface fxp0.0;
            }
        }
        telnet {
            connection-limit 0;
        }
    }
    login {
        message "AUTHORIZED ACCESS ONLY. ACTIVITY IS MONITORED.";
    }
    ntp {
        server 192.0.2.123;
        server 192.0.2.124;
    }
    syslog {
        host 192.0.2.60 {
            any info;
        }
        host 192.0.2.61 {
            any info;
        }
}
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 192.0.2.10/24;
            }
        }
    }
}
protocols {
    lldp {
        interface all;
    }
}
