system {
    host-name SRX-DATACENTER-03;
    services {
        ssh {
            protocol-version v2;
            root-login deny;
        }
        web-management {
            https {
                system-generated-certificate;
            }
        }
    }
    login {
        message "Authorized personnel only.";
    }
    ntp {
        server 203.0.113.123;
    }
    syslog {
        host 203.0.113.60 {
            any info;
        }
    }
    authentication-order [ radius password ];
}
access {
    profile ADMIN-MGMT {
        allow-address 203.0.113.0/24;
    }
}
interfaces {
    ge-0/0/0 {
        unit 0 {
            family inet {
                address 203.0.113.10/24;
            }
        }
    }
}
protocols {
    lldp {
        interface ge-0/0/0;
    }
}
