# config-version=FG100F-7.2.8-FW-build1639-240313:opmode=nat:vdom=root:0
# conf_file_ver=2148283460830001
# buildno=1639
# global_vdom=1
config system global
    set hostname "HQ-FGT-01"
    set admintimeout 480
    set admin-ssh-v1 enable
    set pre-login-banner enable
    set admin-lockout-threshold 20
    set gui-theme mariner
end
config system settings
    set opmode nat
    set ip-src-routing disable
    set ssl-min-proto-ver tls1-2
end
config system admin
    edit "netops"
        set accprofile "super_admin"
        set password ENC SH2kX9vQ2mB7pL4sT8wY1zR6nC3dF5gH0jK2lM4nP6qR8sT0vW2xY4zA6bC8dE0f=
    next
end
config system interface
    edit "wan1"
        set vdom "root"
        set ip 198.51.100.2 255.255.255.248
        set allowaccess ping https ssh http telnet
        set type physical
        set lldp-transmission disable
        set role wan
        set snmp-index 1
    next
    edit "internal"
        set vdom "root"
        set ip 10.1.0.1 255.255.255.0
        set allowaccess ping https ssh
        set type physical
        set role lan
        set snmp-index 2
    next
end
config system snmp sysinfo
    set status enable
end
config system snmp community
    purge
end
config log syslogd setting
    set status enable
    set server "10.99.0.100"
    set port 514
end
config system ntp
    set ntpsync enable
    set type custom
    set authentication enable
    config ntpserver
        edit 1
            set server "10.99.0.10"
            set key-id 1
        next
    end
    config ntp-keys
        edit 1
            set key "ntpauthkeysecret123"
        next
    end
end
config system password-policy
    set status enable
    set minimum-length 12
end
config vpn ipsec phase1-interface
    edit "vpn-to-dc"
        set interface "wan1"
        set peertype any
        set net-device disable
        set proposal aes256-sha256
        set dhgrp 14 19
        set remote-gw 198.51.100.30
        set psksecret "Str0ngVPNP@ssw0rd!"
    next
end
config firewall policy
    edit 1
        set name "Internet-Access"
        set srcintf "internal"
        set dstintf "wan1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "HTTP" "HTTPS" "DNS" "PING"
        set logtraffic all
        set nat enable
    next
end
